trigger:
  - main

jobs:
  - job: Build
    displayName: "Build job"
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: Lambdatest.lambda-azure-pipeline-extention.configuration-task.configuration@1
        displayName: "LambdaTest configuration setup"
        inputs:
          connection: Extent

        env:
          LT_BUILD_NAME: "TestNG With Java"

      - script: |
          mvn test -D suite=parallel.xml

      - task: Lambdatest.lambda-azure-pipeline-extention.showResults-task.LambdatestResults@1
        displayName: "Lambdatest Results"
        env:
          LT_BUILD_NAME: "TestNG With Java"
